[package]
name = "fbla_2024_Project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.6.0"
surrealdb = "1.5.0"
serde = "1.0.202"
tokio = "1.37.0"
